name = "ast1060-spdm-responder"
target = "thumbv7em-none-eabihf"
board = "ast1060-rot"
chip = "../../chips/ast1060"
stacksize = 1024

[kernel]
name = "ast1060-spdm-responder"
requires = {flash = 32000, ram = 8192}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 4096}
start = true
stacksize = 1536
notifications = ["fault", "timer"]

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[tasks.uart_driver]
name = "drv-ast1060-uart"
priority = 2
max-sizes = {flash = 8192, ram = 2048}
uses = ["uart"]
start = true
notifications = ["uart-irq"]
interrupts = {"uart.irq" = "uart-irq"}
# task-slots = ["rcc_driver"]

[tasks.spdm_responder]
name = "drv-spdm-responder-server"
priority = 3
max-sizes = {flash = 16384, ram = 4096}
start = true

[tasks.helloworld]
name = "task-helloworld"
priority = 4
max-sizes = {flash = 8192, ram = 2048}
uses = ["uart"]
start = true
task-slots = ["uart_driver", "spdm_responder"]
